### ISSUE TITLE
tests finish with "Exception ignored"

### ISSUE THREAD

**Issue by schuyler1d** [move-coop/parsons#551]
When running the tests with Python 3.7.3 and master (9bf7ac6c79194491fc628e09ddfac9c74c9351cc) branch, I get the following error when I run `pytest --rootdir ./  test/` from root:

```
Exception ignored in: <function TempDirectory.__del__ at 0x7f2f0268a048>
Traceback (most recent call last):
  File "/home/sky/sb/moveon/parsons/parsons/utilities/files.py", line 352, in __del__
  File "/home/sky/sb/moveon/parsons/parsons/utilities/files.py", line 369, in remove
  File "/home/sky/sb/moveon/parsons/ve37/lib/python3.7/shutil.py", line 506, in rmtree
AttributeError: 'NoneType' object has no attribute 'path'
Exception ignored in: <function TempDirectory.__del__ at 0x7f2f0268a048>
Traceback (most recent call last):
  File "/home/sky/sb/moveon/parsons/parsons/utilities/files.py", line 352, in __del__
  File "/home/sky/sb/moveon/parsons/parsons/utilities/files.py", line 369, in remove
  File "/home/sky/sb/moveon/parsons/ve37/lib/python3.7/shutil.py", line 506, in rmtree
AttributeError: 'NoneType' object has no attribute 'path'
```

This is non-fatal, but it seems like something that should be fixed.

**Comment by shaunagm** [comment]
Not sure this is even still relevant (since we're past Python 3.7, and I haven't seen this reported again) but I'll keep it open as a low priority unless someone can confirm it's no longer an issue.
